language: csharp
sudo: required
dist: trusty

mono: none
dotnet: 1.0.0-preview2-003131

branches:  
  only:
    - master
    
script:
  - cd src/GroupProject/
  - dotnet restore && npm install
  - gulp compile
  - dotnet bundle
  - dotnet --verbose build -c Release
  - cd ../Test
  - dotnet restore
  - dotnet test