language: csharp
sudo: required
dist: trusty

mono: none
dotnet: 1.0.0

branches:  
  only:
    - master
    
script:
  - cd src/GroupProject/
  - dotnet restore && npm install
  - dotnet --verbose build -c Release
  - gulp compile
  - dotnet bundle
  - gulp clean:prod
  # build and run tests
  - cd ../Test
  - dotnet restore
  - dotnet test