language: csharp
solution: GroupProject.sln
sudo: required
dist: trusty

mono: none
dotnet: 1.0.0-preview2-003131

branches:  
  only:
    - master
    
script:
  # Run a new console app
  - dotnet restore
  - cd src/GroupProject/
  - dotnet --verbose build
